//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelAndAPI
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/ModelAndAPI")]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private ModelAndAPI.Picture[] PicturesField;
        
        private string nameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelAndAPI.Picture[] Pictures
        {
            get
            {
                return this.PicturesField;
            }
            set
            {
                this.PicturesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Picture", Namespace="http://schemas.datacontract.org/2004/07/ModelAndAPI")]
    public partial class Picture : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ModelAndAPI.Event EventField;
        
        private ModelAndAPI.Location LocationField;
        
        private ModelAndAPI.Person[] PeopleField;
        
        private string creation_dateField;
        
        private string event1Field;
        
        private string location1Field;
        
        private int nameField;
        
        private string other_detailsField;
        
        private string pathField;
        
        private string personsField;
        
        private string typeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelAndAPI.Event Event
        {
            get
            {
                return this.EventField;
            }
            set
            {
                this.EventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelAndAPI.Location Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelAndAPI.Person[] People
        {
            get
            {
                return this.PeopleField;
            }
            set
            {
                this.PeopleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string creation_date
        {
            get
            {
                return this.creation_dateField;
            }
            set
            {
                this.creation_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="event")]
        public string event1
        {
            get
            {
                return this.event1Field;
            }
            set
            {
                this.event1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="location")]
        public string location1
        {
            get
            {
                return this.location1Field;
            }
            set
            {
                this.location1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string other_details
        {
            get
            {
                return this.other_detailsField;
            }
            set
            {
                this.other_detailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string persons
        {
            get
            {
                return this.personsField;
            }
            set
            {
                this.personsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/ModelAndAPI")]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ModelAndAPI.Picture[] PicturesField;
        
        private string nameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelAndAPI.Picture[] Pictures
        {
            get
            {
                return this.PicturesField;
            }
            set
            {
                this.PicturesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/ModelAndAPI")]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ModelAndAPI.Picture[] PicturesField;
        
        private string nameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ModelAndAPI.Picture[] Pictures
        {
            get
            {
                return this.PicturesField;
            }
            set
            {
                this.PicturesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyInterface")]
public interface MyInterface
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceEvent/deleteEvent", ReplyAction="http://tempuri.org/InterfaceEvent/deleteEventResponse")]
    void deleteEvent(ModelAndAPI.Event e);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceEvent/deleteEvent", ReplyAction="http://tempuri.org/InterfaceEvent/deleteEventResponse")]
    System.Threading.Tasks.Task deleteEventAsync(ModelAndAPI.Event e);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceEvent/addEvent", ReplyAction="http://tempuri.org/InterfaceEvent/addEventResponse")]
    void addEvent(ModelAndAPI.Event e);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceEvent/addEvent", ReplyAction="http://tempuri.org/InterfaceEvent/addEventResponse")]
    System.Threading.Tasks.Task addEventAsync(ModelAndAPI.Event e);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceLocation/deleteLocation", ReplyAction="http://tempuri.org/InterfaceLocation/deleteLocationResponse")]
    void deleteLocation(ModelAndAPI.Location l);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceLocation/deleteLocation", ReplyAction="http://tempuri.org/InterfaceLocation/deleteLocationResponse")]
    System.Threading.Tasks.Task deleteLocationAsync(ModelAndAPI.Location l);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceLocation/addLocation", ReplyAction="http://tempuri.org/InterfaceLocation/addLocationResponse")]
    void addLocation(ModelAndAPI.Location l);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceLocation/addLocation", ReplyAction="http://tempuri.org/InterfaceLocation/addLocationResponse")]
    System.Threading.Tasks.Task addLocationAsync(ModelAndAPI.Location l);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/deletePerson", ReplyAction="http://tempuri.org/InterfacePerson/deletePersonResponse")]
    void deletePerson(ModelAndAPI.Person p);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/deletePerson", ReplyAction="http://tempuri.org/InterfacePerson/deletePersonResponse")]
    System.Threading.Tasks.Task deletePersonAsync(ModelAndAPI.Person p);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/addPerson", ReplyAction="http://tempuri.org/InterfacePerson/addPersonResponse")]
    void addPerson(ModelAndAPI.Person p);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/addPerson", ReplyAction="http://tempuri.org/InterfacePerson/addPersonResponse")]
    System.Threading.Tasks.Task addPersonAsync(ModelAndAPI.Person p);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/insertPicture", ReplyAction="http://tempuri.org/InterfacePicture/insertPictureResponse")]
    void insertPicture(ModelAndAPI.Picture p);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/insertPicture", ReplyAction="http://tempuri.org/InterfacePicture/insertPictureResponse")]
    System.Threading.Tasks.Task insertPictureAsync(ModelAndAPI.Picture p);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/deletePicture", ReplyAction="http://tempuri.org/InterfacePicture/deletePictureResponse")]
    void deletePicture(ModelAndAPI.Picture p);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/deletePicture", ReplyAction="http://tempuri.org/InterfacePicture/deletePictureResponse")]
    System.Threading.Tasks.Task deletePictureAsync(ModelAndAPI.Picture p);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/updatePicture", ReplyAction="http://tempuri.org/InterfacePicture/updatePictureResponse")]
    void updatePicture(ModelAndAPI.Picture p);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/updatePicture", ReplyAction="http://tempuri.org/InterfacePicture/updatePictureResponse")]
    System.Threading.Tasks.Task updatePictureAsync(ModelAndAPI.Picture p);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/getPicture", ReplyAction="http://tempuri.org/InterfacePicture/getPictureResponse")]
    ModelAndAPI.Picture getPicture(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/getPicture", ReplyAction="http://tempuri.org/InterfacePicture/getPictureResponse")]
    System.Threading.Tasks.Task<ModelAndAPI.Picture> getPictureAsync(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/getPictures", ReplyAction="http://tempuri.org/InterfacePicture/getPicturesResponse")]
    ModelAndAPI.Picture[] getPictures(string query);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/getPictures", ReplyAction="http://tempuri.org/InterfacePicture/getPicturesResponse")]
    System.Threading.Tasks.Task<ModelAndAPI.Picture[]> getPicturesAsync(string query);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface MyInterfaceChannel : MyInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MyInterfaceClient : System.ServiceModel.ClientBase<MyInterface>, MyInterface
{
    
    public MyInterfaceClient()
    {
    }
    
    public MyInterfaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MyInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void deleteEvent(ModelAndAPI.Event e)
    {
        base.Channel.deleteEvent(e);
    }
    
    public System.Threading.Tasks.Task deleteEventAsync(ModelAndAPI.Event e)
    {
        return base.Channel.deleteEventAsync(e);
    }
    
    public void addEvent(ModelAndAPI.Event e)
    {
        base.Channel.addEvent(e);
    }
    
    public System.Threading.Tasks.Task addEventAsync(ModelAndAPI.Event e)
    {
        return base.Channel.addEventAsync(e);
    }
    
    public void deleteLocation(ModelAndAPI.Location l)
    {
        base.Channel.deleteLocation(l);
    }
    
    public System.Threading.Tasks.Task deleteLocationAsync(ModelAndAPI.Location l)
    {
        return base.Channel.deleteLocationAsync(l);
    }
    
    public void addLocation(ModelAndAPI.Location l)
    {
        base.Channel.addLocation(l);
    }
    
    public System.Threading.Tasks.Task addLocationAsync(ModelAndAPI.Location l)
    {
        return base.Channel.addLocationAsync(l);
    }
    
    public void deletePerson(ModelAndAPI.Person p)
    {
        base.Channel.deletePerson(p);
    }
    
    public System.Threading.Tasks.Task deletePersonAsync(ModelAndAPI.Person p)
    {
        return base.Channel.deletePersonAsync(p);
    }
    
    public void addPerson(ModelAndAPI.Person p)
    {
        base.Channel.addPerson(p);
    }
    
    public System.Threading.Tasks.Task addPersonAsync(ModelAndAPI.Person p)
    {
        return base.Channel.addPersonAsync(p);
    }
    
    public void insertPicture(ModelAndAPI.Picture p)
    {
        base.Channel.insertPicture(p);
    }
    
    public System.Threading.Tasks.Task insertPictureAsync(ModelAndAPI.Picture p)
    {
        return base.Channel.insertPictureAsync(p);
    }
    
    public void deletePicture(ModelAndAPI.Picture p)
    {
        base.Channel.deletePicture(p);
    }
    
    public System.Threading.Tasks.Task deletePictureAsync(ModelAndAPI.Picture p)
    {
        return base.Channel.deletePictureAsync(p);
    }
    
    public void updatePicture(ModelAndAPI.Picture p)
    {
        base.Channel.updatePicture(p);
    }
    
    public System.Threading.Tasks.Task updatePictureAsync(ModelAndAPI.Picture p)
    {
        return base.Channel.updatePictureAsync(p);
    }
    
    public ModelAndAPI.Picture getPicture(string name)
    {
        return base.Channel.getPicture(name);
    }
    
    public System.Threading.Tasks.Task<ModelAndAPI.Picture> getPictureAsync(string name)
    {
        return base.Channel.getPictureAsync(name);
    }
    
    public ModelAndAPI.Picture[] getPictures(string query)
    {
        return base.Channel.getPictures(query);
    }
    
    public System.Threading.Tasks.Task<ModelAndAPI.Picture[]> getPicturesAsync(string query)
    {
        return base.Channel.getPicturesAsync(query);
    }
}
