//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/ModelAndAPI")]
    public partial class Event : object
    {
        
        private int IdField;
        
        private System.Collections.Generic.List<ServiceReference.Picture> PicturesField;
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference.Picture> Pictures
        {
            get
            {
                return this.PicturesField;
            }
            set
            {
                this.PicturesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Picture", Namespace="http://schemas.datacontract.org/2004/07/ModelAndAPI")]
    public partial class Picture : object
    {
        
        private ServiceReference.Event EventField;
        
        private ServiceReference.Location LocationField;
        
        private System.Collections.Generic.List<ServiceReference.Person> PeopleField;
        
        private string creation_dateField;
        
        private string eventField;
        
        private string locationField;
        
        private int nameField;
        
        private string other_detailsField;
        
        private string pathField;
        
        private string personsField;
        
        private string typeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.Event Event
        {
            get
            {
                return this.EventField;
            }
            set
            {
                this.EventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.Location Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference.Person> People
        {
            get
            {
                return this.PeopleField;
            }
            set
            {
                this.PeopleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string creation_date
        {
            get
            {
                return this.creation_dateField;
            }
            set
            {
                this.creation_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string @event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string other_details
        {
            get
            {
                return this.other_detailsField;
            }
            set
            {
                this.other_detailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string persons
        {
            get
            {
                return this.personsField;
            }
            set
            {
                this.personsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/ModelAndAPI")]
    public partial class Location : object
    {
        
        private System.Collections.Generic.List<ServiceReference.Picture> PicturesField;
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference.Picture> Pictures
        {
            get
            {
                return this.PicturesField;
            }
            set
            {
                this.PicturesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/ModelAndAPI")]
    public partial class Person : object
    {
        
        private System.Collections.Generic.List<ServiceReference.Picture> PicturesField;
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReference.Picture> Pictures
        {
            get
            {
                return this.PicturesField;
            }
            set
            {
                this.PicturesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.MyInterface")]
    public interface MyInterface
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceEvent/deleteEvent", ReplyAction="http://tempuri.org/InterfaceEvent/deleteEventResponse")]
        System.Threading.Tasks.Task deleteEventAsync(ServiceReference.Event e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceEvent/addEvent", ReplyAction="http://tempuri.org/InterfaceEvent/addEventResponse")]
        System.Threading.Tasks.Task addEventAsync(ServiceReference.Event e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceLocation/deleteLocation", ReplyAction="http://tempuri.org/InterfaceLocation/deleteLocationResponse")]
        System.Threading.Tasks.Task deleteLocationAsync(ServiceReference.Location l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceLocation/addLocation", ReplyAction="http://tempuri.org/InterfaceLocation/addLocationResponse")]
        System.Threading.Tasks.Task addLocationAsync(ServiceReference.Location l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/deletePerson", ReplyAction="http://tempuri.org/InterfacePerson/deletePersonResponse")]
        System.Threading.Tasks.Task deletePersonAsync(ServiceReference.Person p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePerson/addPerson", ReplyAction="http://tempuri.org/InterfacePerson/addPersonResponse")]
        System.Threading.Tasks.Task addPersonAsync(ServiceReference.Person p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/insertPicture", ReplyAction="http://tempuri.org/InterfacePicture/insertPictureResponse")]
        System.Threading.Tasks.Task insertPictureAsync(ServiceReference.Picture p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/deletePicture", ReplyAction="http://tempuri.org/InterfacePicture/deletePictureResponse")]
        System.Threading.Tasks.Task deletePictureAsync(ServiceReference.Picture p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/updatePicture", ReplyAction="http://tempuri.org/InterfacePicture/updatePictureResponse")]
        System.Threading.Tasks.Task updatePictureAsync(ServiceReference.Picture p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/getPicture", ReplyAction="http://tempuri.org/InterfacePicture/getPictureResponse")]
        System.Threading.Tasks.Task<ServiceReference.Picture> getPictureAsync(int name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePicture/getPictures", ReplyAction="http://tempuri.org/InterfacePicture/getPicturesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference.Picture>> getPicturesAsync(string query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface MyInterfaceChannel : ServiceReference.MyInterface, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MyInterfaceClient : System.ServiceModel.ClientBase<ServiceReference.MyInterface>, ServiceReference.MyInterface
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MyInterfaceClient() : 
                base(MyInterfaceClient.GetDefaultBinding(), MyInterfaceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_Interface.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyInterfaceClient(EndpointConfiguration endpointConfiguration) : 
                base(MyInterfaceClient.GetBindingForEndpoint(endpointConfiguration), MyInterfaceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyInterfaceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MyInterfaceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyInterfaceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MyInterfaceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task deleteEventAsync(ServiceReference.Event e)
        {
            return base.Channel.deleteEventAsync(e);
        }
        
        public System.Threading.Tasks.Task addEventAsync(ServiceReference.Event e)
        {
            return base.Channel.addEventAsync(e);
        }
        
        public System.Threading.Tasks.Task deleteLocationAsync(ServiceReference.Location l)
        {
            return base.Channel.deleteLocationAsync(l);
        }
        
        public System.Threading.Tasks.Task addLocationAsync(ServiceReference.Location l)
        {
            return base.Channel.addLocationAsync(l);
        }
        
        public System.Threading.Tasks.Task deletePersonAsync(ServiceReference.Person p)
        {
            return base.Channel.deletePersonAsync(p);
        }
        
        public System.Threading.Tasks.Task addPersonAsync(ServiceReference.Person p)
        {
            return base.Channel.addPersonAsync(p);
        }
        
        public System.Threading.Tasks.Task insertPictureAsync(ServiceReference.Picture p)
        {
            return base.Channel.insertPictureAsync(p);
        }
        
        public System.Threading.Tasks.Task deletePictureAsync(ServiceReference.Picture p)
        {
            return base.Channel.deletePictureAsync(p);
        }
        
        public System.Threading.Tasks.Task updatePictureAsync(ServiceReference.Picture p)
        {
            return base.Channel.updatePictureAsync(p);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Picture> getPictureAsync(int name)
        {
            return base.Channel.getPictureAsync(name);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference.Picture>> getPicturesAsync(string query)
        {
            return base.Channel.getPicturesAsync(query);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Interface))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Interface))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/MY-PC");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MyInterfaceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_Interface);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MyInterfaceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_Interface);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_Interface,
        }
    }
}
